### ISSUE TITLE
Do not import `@jest/globals` outside of the Jest test environment

### ISSUE THREAD

**Issue by rhysawilliams2010** [eugene-manuilov/jest-runner-groups#11]
Hello,

I have upgraded my project to jest 25.5.0 and I found that if I try to use jest-runner-groups I get:
```
Do not import `@jest/globals` outside of the Jest test environment
```

I think it was introduced with this change in jest: https://github.com/facebook/jest/commit/e21468da33a2f3c9c2b9af0dcfba14b002737f60

You can reproduce with this test using jest 25.5+:
```
jest.disableAutomock()

test('fml', () => {
  expect(true).toBeTruthy()
})

```

If I downgrade to jest 25.4.0 or disable jest-runner-groups the tests run as expected.

I have no idea what's going on here to offer PR sorry.

**Comment by eugene-manuilov** [comment]
Hi @rhysawilliams2010 

can you show me your jest config? I can't replicate this issue on my end.

**Comment by rhysawilliams2010** [comment]
```
module.exports = {
  setupFiles: ['dotenv/config'],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  rootDir: './src',
  preset: 'ts-jest',
  testPathIgnorePatterns: [
    '<rootDir>.*/__test-utils__/',
  ],
  collectCoverage: false,
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  forceExit: true,
  runner: 'jest-runner-groups',
  testRunner: 'jest-circus/runner',
  globals: {
    'ts-jest': {
      isolatedModules: true
    }
  }
}
```

**Comment by eugene-manuilov** [comment]
Hm... it's weird but i still can't reproduce this issue... @rhysawilliams2010 can you comment out `setupFiles` and `setupFilesAfterEnv` config settings and try to run tests without it? Or can you create a temporary repo which reproduces the issue?

**Comment by rhysawilliams2010** [comment]
Hi @eugene-manuilov thank you for checking this for me. I set up a minimal repo to try and repo the error, but I could not reproduce the error. 
I tried upgrading my original project again and everything works absolutely fine. 
I am very sorry to have wasted your time.

**Comment by eugene-manuilov** [comment]
No worries, @rhysawilliams2010

**Comment by thinkjson** [comment]
I'm having the same issue. We don't even explicitly import @jest/globals, so I suspect it's ts-node or similar that is causing an issue. What did you upgrade in order to get it working?

**Comment by eugene-manuilov** [comment]
Hi @thinkjson 

which version of the `jest-runner-groups` do you use?

**Comment by thinkjson** [comment]
Latest - 2.0.1

**Comment by eugene-manuilov** [comment]
@thinkjson can you create a test repo which reproduces the issue?
