### ISSUE TITLE
Unrecognized CLI Parameter

### ISSUE THREAD

**Issue by milliechan** [eugene-manuilov/jest-runner-groups#2]
Hi there! We have followed the instructions in the readme but have run across this error message when trying to run jest with the group flag.

Anything else we should be looking into? 
![image](https://user-images.githubusercontent.com/11792174/70190670-6781cd00-16ab-11ea-96db-6993311cd4e4.png)

**Comment by eugene-manuilov** [comment]
Hi @milliechan 

could you please show me your jest config and a command that you use to run tests with groups? Also it would be handy if you tell me which version of jest you use. Thanks in advance.

**Comment by milliechan** [comment]
All good! We were running an older version of jest. Thanks for your help!
