### ISSUE TITLE
Run tests not in a group or exclude a group

### ISSUE THREAD

**Issue by thewilkybarkid** [eugene-manuilov/jest-runner-groups#4]
Is it possible to run tests that are not in a group (eg to save having to group lots of tests as `@group unit`), or to not run tests from a certain group (eg to not run those in `@group integration`?)

**Comment by eugene-manuilov** [comment]
hi @thewilkybarkid 

just published a new version that allows you to use minus (`-`) character at the beginning of a group name to exclude it. For example, run all `foo` tests, but not `foo/baz`:

```
jest --group=foo --group=-foo/baz
```

Is it what you need?

**Comment by thewilkybarkid** [comment]
Seems to work well, thanks! ✨
