### ISSUE TITLE
jest-runner-groups does not work with the jest --testRunner CLI parameter

### ISSUE THREAD

**Issue by timrobinson33** [eugene-manuilov/jest-runner-groups#7]
I'm using create-react-app which doesn't allow specifying the test runner in config. However, the guys there suggested I could use the CLI option to specify the test runner. I have tried adding `--testRunner="jest-runner-groups"` but this gives an error:

`TypeError: Class constructor GroupRunner cannot be invoked without 'new'`

I am using TypeScript. I can see that your GroupRunner is inheriting from jest-runner's TestRunner class but according to the jest documentation (https://jestjs.io/docs/en/configuration), a test runner should be a function with a certain signature so I'm confused how the 2 concepts fit together.

**Comment by eugene-manuilov** [comment]
Hi @timrobinson33 

I believe you need to use `--runner=groups` instead of `--testRunner="jest-runner-groups"`. Could you please try it and let me know if it helps?

**Comment by timrobinson33** [comment]
Thanks, it seems to be trying to do the right thing now (not sure why the `--runner` option isn't in the documentation but that's another story). However I now get a different error:

```
TypeError: this._config.extraGlobals is not iterable

      at Runtime.constructInjectedModuleParameters (node_modules/jest-runner-groups/node_modules/jest-runtime/build/index.js:1522:23)
          at Array.forEach (<anonymous>)

```
I'm getting this error even if the test is empty. I'm using jest 24.9 (which is the version included in the latest create-react-app scripts), and also I'm using typescript in case that has any impact.

**Comment by eugene-manuilov** [comment]
@timrobinson33 can you try to install and use `jest-runner-groups@1.1.0` instead of version `1.1.1`? Does it help?

**Comment by timrobinson33** [comment]
Woo Hoo :-)  Yes that's working for me now thanks. And it's much faster running than using -t to filter the tests by name
