### ISSUE TITLE
TypeError: this._config.extraGlobals is not iterable

### ISSUE THREAD

**Issue by adamcypher** [eugene-manuilov/jest-runner-groups#9]
TypeError: this._config.extraGlobals is not iterable
at Runtime.constructInjectedModuleParameters (../../node_modules/jest-runtime/build/index.js:1759:23)

Jest 24.9.0

**Comment by eugene-manuilov** [comment]
Hi @adamgering 

you need to upgrade jest to the latest version or downgrade jest-runner-groups to 1.1.0

**Comment by adamcypher** [comment]
Jest 24.9.0 is the current version for create-react-app
If you want to create a bugfix version (1.1.0 -> 1.1.1) that is incompatible with the current version of create-react-app, you should document the fact ... or better yet, use semver properly and indicate a breaking version update (1.1.0 -> 2.0.0).

I would recommend people use the jest `--testNamePattern=` and not use your package. Adding poorly tested third-party libraries is bad idea, I won't make the mistake again.

**Comment by adamcypher** [comment]
Sorry to be harsh, but it needs to be said.

**Comment by eugene-manuilov** [comment]
@adamgering the current version of jest is 26+, why did you come here and yell at me? Go to create-react-app repo and do yell at them to force them to upgrade jest to the latest version. The world doesn't spin around create-react-app. I have never worked with create-react-app and have no clue what it uses.

Anyway, i'm planing to work on a new version of this runner which will support jest 24.x.x and 25+ versions.

**Comment by eugene-manuilov** [comment]
Ok, i have updated this package to work with jest@24.9.0 and higher, and published it as 2.0.0. Plus, added compatibility tests to make sure it works with jest@24.9.0 and jest@25+. Going to close this thread.
